'use client';

import { useQuery } from '@tanstack/react-query';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { useTripContext } from './TripContext';
import { fetchSettlement } from '@/lib/api';

export function SettlementPanel() {
  const { currentTrip } = useTripContext();

  const { data } = useQuery({
    queryKey: ['settlement', currentTrip?.id],
    queryFn: () => fetchSettlement(currentTrip!.id),
    enabled: !!currentTrip,
  });

  const settlements = data?.settlements || [];
  const ledger = data?.ledger || [];

  const handleExportPDF = () => {
    const content = `
SETTLEMENT SUMMARY
${currentTrip?.name || 'Trip'}
Generated: ${new Date().toLocaleString('en-IN')}

${'='.repeat(50)}

BALANCES:
${ledger.map((l) => `${l.memberName}: ₹${l.netBalance.toLocaleString('en-IN', { maximumFractionDigits: 0 })} ${l.netBalance > 0 ? '(to receive)' : l.netBalance < 0 ? '(to pay)' : '(settled)'}`).join('\n')}

${'='.repeat(50)}

SETTLEMENTS:
${settlements.length > 0 ? settlements.map((s) => `${s.fromMemberName} pays ${s.toMemberName}: ₹${s.amount.toLocaleString('en-IN', { maximumFractionDigits: 0 })} (RM ${s.amountInMYR?.toLocaleString('en-IN', { maximumFractionDigits: 0 })})`).join('\n') : 'No settlements required - everyone is settled!'}

${'='.repeat(50)}
Generated by Split MYR
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${currentTrip?.name || 'trip'}-settlement-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShareWhatsApp = () => {
    let message = `*${currentTrip?.name || 'Trip'} Settlement*\n\n`;
    if (settlements.length === 0) {
      message += 'Everyone is settled! No payments needed.';
    } else {
      message += '*Payments Required:*\n';
      settlements.forEach((s) => {
        message += `• ${s.fromMemberName} ➜ ${s.toMemberName}: ₹${s.amount.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`;
        if (s.amountInMYR) message += ` (RM ${s.amountInMYR.toLocaleString('en-IN', { maximumFractionDigits: 0 })})`;
        message += '\n';
      });
    }
    message += `\n_Generated by Split MYR_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank');
  };

  if (!currentTrip) {
    return (
      <Card>
        <CardHeader><CardTitle>Settlement</CardTitle></CardHeader>
        <CardContent><p className="text-muted-foreground">Select a trip to view settlements.</p></CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center justify-between">
          <span>Settlement</span>
          <Badge variant="outline">Minimized Payments</Badge>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {settlements.length > 0 ? (
          <>
            <div className="space-y-3">
              {settlements.map((settlement, idx) => (
                <div key={idx} className="p-4 border rounded-lg bg-gradient-to-r from-red-50 to-green-50 dark:from-red-950/20 dark:to-green-950/20">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className="text-center">
                        <div className="font-semibold text-red-600">{settlement.fromMemberName}</div>
                        <div className="text-xs text-muted-foreground">pays</div>
                      </div>
                      <div className="text-2xl">→</div>
                      <div className="text-center">
                        <div className="font-semibold text-green-600">{settlement.toMemberName}</div>
                        <div className="text-xs text-muted-foreground">receives</div>
                      </div>
                    </div>
                    <div className="text-right">
                      <div className="font-bold text-lg">₹{settlement.amount.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</div>
                      {settlement.amountInMYR && <div className="text-sm text-muted-foreground">≈ RM {settlement.amountInMYR.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</div>}
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <Separator />
            <div className="flex gap-2">
              <Button variant="outline" className="flex-1" onClick={handleExportPDF}>Export Summary</Button>
              <Button variant="outline" className="flex-1" onClick={handleShareWhatsApp}>Share via WhatsApp</Button>
            </div>
          </>
        ) : (
          <div className="text-center py-8">
            <div className="text-4xl mb-2">🎉</div>
            <h3 className="font-semibold text-lg mb-1">All Settled!</h3>
            <p className="text-muted-foreground">{currentTrip.members?.length === 0 ? 'Add members and expenses to see settlements.' : 'Everyone is square. No payments needed.'}</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
